# Site settings
title: BlueRobotics Product Documentation Chinese Localization Site
email: info@robodock.net
description: > # this means to ignore newlines until "baseurl:"
  The documentation site has instructions, tutorials, and guides for
  using BlueRobotics' products. You can contribute through Github!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bluerov.robodock.net"
twitter_username: robodock
github_username:  robodock

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
